# Generated by Django 3.1.3 on 2020-11-13 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_recipes', models.ManyToManyField(to='recipe.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ManyToManyField(to='recipe.Recipe')),
                ('user_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.userdetail')),
            ],
        ),
    ]
