# Generated by Django 3.1.3 on 2020-11-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_auto_20201115_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencerecipe',
            name='user_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencerecipe', to='mypage.userdetail'),
        ),
    ]
