# Generated by Django 3.1.3 on 2020-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_auto_20201115_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencerecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='experiencerecipe',
            name='recipe',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
