# Generated by Django 3.1.3 on 2020-11-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('mypage', '0005_auto_20201115_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencerecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
